services:
  db:
    image: postgres
    container_name: local_pgdb1
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    expose:
      - "5433"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container1
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: